apiVersion: apps/v1
kind: Deployment

metadata:
  name: inference
  namespace: smart-parking

spec:
  replicas: 1

  selector:
    matchLabels:
      app: inference

  template:
    metadata:
      labels:
        app: inference

    spec:

      containers:

      - name: inference

        image: inference-program:latest

        imagePullPolicy: Never

        env:

        - name: RABBITMQ_HOST
          value: rabbitmq

        - name: REDIS_HOST
          value: redis

        - name: MONGO_HOST
          value: mongodb

        resources:

          requests:
            cpu: "250m"
            memory: "512Mi"

          limits:
            cpu: "1"
            memory: "1Gi"