apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-pod
  namespace: smart-parking
  labels:
    app: inference-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-pod
  template:
    metadata:
      labels:
        app: inference-pod
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: inference-container
        image: inference-pod:v1
        imagePullPolicy: IfNotPresent
        command: ["python", "-u", "InferencePod.py"]
        resources:
          requests:
            memory: "350Mi"
            cpu: "250m"
          limits:
            memory: "800Mi"
            cpu: "750m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: YOLO_CONFIG_DIR
          value: "/tmp"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: MONGO_HOST
          value: "mongodb"
        - name: REDIS_HOST
          value: "redis"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: MONGO_PORT
          value: "27017"
        - name: REDIS_PORT
          value: "6379"