#init pod

apiVersion: batch/v1
kind: Job
metadata:
  name: smart-parking-init
  namespace: smart-parking
  labels:
    app: smart-parking-init
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: smart-parking-init
    spec:
      containers:
      - name: init-container
        image: smart-parking-init:v1
        imagePullPolicy: Always
        command: ["python", "Init.py"]
        env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
      restartPolicy: OnFailure

    #ets workeng