apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: smart-parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "256Mi"   # Minimum RAM requested/guaranteed
          limits:
            memory: "512Mi"   # Maximum RAM allowed before potential OOM-kill