apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: inference-scaler
  namespace: smart-parking
spec:
  scaleTargetRef:
    name: inference-pod
  minReplicaCount: 1
  maxReplicaCount: 8
  pollingInterval: 1
  cooldownPeriod: 60
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: requests
      mode: QueueLength
      value: "20"
      host: amqp://guest:guest@rabbitmq.smart-parking.svc.cluster.local:5672/